### ISSUE TITLE
BlockTT does not support CUDA Tensor as indices

### ISSUE THREAD

**Issue by JeremieMelo** [tensorly/torch#23]
When I use FactorizedEmbedding, I found that it does not support CUDA Tensor as input indices.
Because in `BlockTT.__getitem__()`, it uses `np.unravel_index(index)`, which cannot take CUDA Tensor as input...
Since PyTorch does not have `unravel_index()` yet, either moving CUDA indices to CPU or writing a Torch Version of `unravel_index()` will fix this bug.

**Comment by JeanKossaifi** [comment]
Do you have a usecase where you need the indices to be on GPU?

Typically, given the size of the indices, the overhead of converting is negligible, but if you have need for supporting torch tensors there we can add that.

**Comment by JeanKossaifi** [comment]
Fixed in #24
